[[bin]]
name = "nearest-exit-from-entrance-in-maze"
path = "src/nearest-exit-from-entrance-in-maze/main.rs"

[package]
name = "leetcoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
